More streamlining

diff --git a/thoroughly-clean b/thoroughly-clean
--- a/thoroughly-clean
+++ b/thoroughly-clean
@@ -2,7 +2,7 @@
 # vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=sh:
 [[ $UID -eq 0 ]] || { echo "ERROR: must be run as root."; exit 1; }
 pushd $(dirname $0) 2>&1 > /dev/null && BASEDIR=$(pwd) && popd 2>&1 > /dev/null
-ZEROFILE="/zerofile"
+[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
 
 function clean_debian_derived
 {
@@ -10,7 +10,6 @@ function clean_debian_derived
 	[[ -f "$PRUNE" ]] || { echo "ERROR: this script must sit inside the working copy of an bitbucket.org/assarbad/dotfiles clone."; exit 1; }
 	source "$PRUNE" || { echo "ERROR: could not include (source) '$PRUNE'."; exit 1; }
 	type prune-kernels 2>&1 > /dev/null || { echo "ERROR: callable 'prune-kernels' does not exist."; exit 1; }
-	[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
 	echo -e "${cW}INFO:${cZ} running ${cG}prune-kernels${cZ}"
 	prune-kernels --old
 	echo -e "${cW}INFO:${cZ} asking apt-get to purge previously removed packages"
@@ -36,30 +35,11 @@ function clean_debian_derived
 		fi
 	done
 	find /etc -type f -name '*.dpkg-old' -delete
-	trap 'rm -f "$ZEROFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
-	echo -e "${cW}INFO:${cZ} zero-filling free space on root"
-	dd if=/dev/zero of=$ZEROFILE bs=10M
-	echo -e "${cW}INFO:${cZ} synchronizing disks"
-	sync
-}
-
-function clean_freebsd
-{
-	echo "Turning swap off"
-	swapoff -a
-	trap 'rm -f "$ZEROFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
-	echo "Zeroing / partition"
-	dd if=/dev/zero of=$ZEROFILE bs=10M || rm -f "$ZEROFILE"
-	SWAP=$(grep swap /etc/fstab|awk '{print $1}')
-	if [[ -n "$SWAP" ]]; then
-		echo "Zeroing swap partition ($SWAP)"
-		dd if=/dev/zero of=$SWAP bs=10M
-	fi
 }
 
 function unsupported
 {
-	echo "ERROR: this script expects a Debian or Debian-derived Linux system or FreeBSD."
+	echo -e "${cR}ERROR:${cZ} this script expects a Debian or Debian-derived Linux system or FreeBSD."
 	exit 1
 }
 
@@ -67,10 +47,46 @@ case $(uname -s) in
 	Linux)
 		[[ -e "/etc/debian_version" ]] || unsupported
 		clean_debian_derived
-		exit 0
 		;;
 	FreeBSD)
-		clean_freebsd
-		exit 0
+		# no special steps, yet!
+		;;
+	*)
+		unsupported
 		;;
 esac
+ZEROFILE="/zerofile"
+if [[ -r /etc/fstab ]]; then
+	SWAP=$(awk '$3 ~ /^swap/ {print $1}' /etc/fstab)
+fi
+
+echo "${cW}INFO:${cZ} turning swap off"
+swapoff -a
+
+for sw in $SWAP; do
+	case $sw in
+		UUID=*)
+			if [[ -e "/dev/disk/by-uuid/${sw#UUID=}" ]]; then
+				echo -e "${cW}INFO:${cZ} zeroing swap partition ($sw)"
+				dd if=/dev/zero of=/dev/disk/by-uuid/${sw#UUID=} bs=10M
+				[[ "Linux" == "$(uname -s)" ]] mkswap "/dev/disk/by-uuid/${sw#UUID=}"
+			fi
+			;;
+		/dev/*)
+			echo -e "${cW}INFO:${cZ} zeroing swap partition ($sw)"
+			dd if=/dev/zero of=$sw bs=10M
+			[[ "Linux" == "$(uname -s)" ]] mkswap "$sw"
+			;;
+		*)
+			echo -e "${cY}WARNING:${cZ} don't know how to handle '$sw' swap space. Skipping."
+			;;
+	esac
+done
+
+trap 'rm -f "$ZEROFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
+echo -e "${cW}INFO:${cZ} zero-filling free space on root"
+# TODO: remove echo
+echo dd if=/dev/zero of=$ZEROFILE bs=10M
+echo -e "${cW}INFO:${cZ} synchronizing disks"
+sync
+echo -e "${cW}PLEASE${cZ} reboot now."
